- name: Deploy Uptime-kuma on K3s cluster
  hosts: master
  gather_facts: false
  become: true
  tasks:

    - name: Create namespace
      kubernetes.core.k8s:
        name: testing
        api_version: v1
        kind: Namespace
        state: present