- name: Deploy Uptime-kuma on K3s cluster
  hosts: master
  gather_facts: false
  become: true
  tasks:

    - name: Create directory for manifest files
      ansible.builtin.file:
        path: ~/manifests/uptime-kuma
        state: directory
        mode: '0755'

    - name: Copy .yaml files to the directory
      ansible.builtin.copy:
        src: /home/rens/k3s_manifests/uptime_kuma/
        dest: ~/manifests/uptime-kuma

    - name: Create persistent storage
      ansible.builtin.shell: >-
        kubectl apply -f uptime-kuma/
      args:
        chdir: ~/manifests/
