- name: Deploy Uptime-kuma on K3s cluster
  hosts: master
  gather_facts: false
  become: true
  tasks:

    - name: Create persistent storage
      ansible.builtin.shell: >-
        kubectl apply -f pvc.yaml
      args:
        chdir: /home/rens/k3s_manifests/uptime_kuma/

    - name: Create deployment
      ansible.builtin.shell: >-
        kubectl apply -f deployment.yaml
      args:
        chdir: /home/rens/k3s_manifests/uptime_kuma/

    - name: Create nodeport service
      ansible.builtin.shell: >-
        kubectl apply -f nodeport.yaml
      args:
        chdir: /home/rens/k3s_manifests/uptime_kuma/

