- name: Update OS with latest packages
  hosts: all
  gather_facts: false
  become: true
  tasks:

    - name: apt-get update && apt-get upgrade
      ansible.builtin.apt:
        name: "*"
        state: present
        update_cache: latest