apiVersion: v1
kind: Deployment
metadata:
  name: semaphore-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semaphore-mysql
  template:
    metadata:
      labels:
        app: semaphore-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: semaphore-mysql-volume
              mountPath: /mnt/share/mysql
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: semaphore
            - name: MYSQL_USER
              value: semaphore
            - name: MYSQL_PASSWORD
              value: semaphore
      volumes:
        - name: semaphore-mysql-volume
          emptyDir: {}
