apiVersion: v1
kind: Service
metadata:
  name: semaphore-ui-nodeport-service
spec:
  selector:
    app: semaphore-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000  # Specify the NodePort (adjust if needed)
  type: NodePort  # Expose externally using NodePort
