apiVersion: v1
kind: Deployment
metadata:
  name: semaphore-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semaphore-ui
  template:
    metadata:
      labels:
        app: semaphore-ui
    spec:
      containers:
        - name: semaphore-ui
          image: semaphoreui/semaphore:latest
          ports:
            - containerPort: 3000
          env:
            - name: SEMAPHORE_DB_USER
              value: semaphore
            - name: SEMAPHORE_DB_HOST
              value: mysql
            - name: SEMAPHORE_DB_PORT
              value: 3306
            - name: SEMAPHORE_DB_DIALECT
              value: mysql
            - name: SEMAPHORE_DB
              value: semaphore
            - name: SEMAPHORE_PLAYBOOK_PATH
              value: /tmp/semaphore/
            - name: SEMAPHORE_ADMIN_PASSWORD
              value: changeme
            - name: SEMAPHORE_ADMIN_NAME
              value: admin
            - name: SEMAPHORE_ADMIN_EMAIL
              value: admin@localhost
            - name: SEMAPHORE_ADMIN
              value: admin
            - name: SEMAPHORE_ACCESS_KEY_ENCRYPTION
              value: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=

            


